export interface IconOption {
  name: string;
  label: string;
  keywords: string;
}

export interface IconSection {
  title: string;
  icons: IconOption[];
}

/** Curated icon catalog organized by section. Keywords power the fuzzy search. */
export const ICON_SECTIONS: IconSection[] = [
  {
    title: "General",
    icons: [
      { name: "i-lucide-wallet", label: "Wallet", keywords: "money cash billfold" },
      { name: "i-lucide-wallet-cards", label: "Wallet Cards", keywords: "money cards payment" },
      { name: "i-lucide-wallet-minimal", label: "Wallet Minimal", keywords: "money cash simple" },
      { name: "i-lucide-landmark", label: "Bank", keywords: "institution finance government" },
      { name: "i-lucide-banknote", label: "Banknote", keywords: "money cash bill paper" },
      { name: "i-lucide-coins", label: "Coins", keywords: "money cash change" },
      { name: "i-lucide-piggy-bank", label: "Piggy Bank", keywords: "savings money kids" },
      { name: "i-lucide-vault", label: "Vault", keywords: "safe secure savings deposit" },
      { name: "i-lucide-hand-coins", label: "Hand Coins", keywords: "payment tip give money" },
      { name: "i-lucide-dollar-sign", label: "Dollar", keywords: "usd money currency america" },
      { name: "i-lucide-circle-dollar-sign", label: "Dollar Circle", keywords: "usd money currency" },
      { name: "i-lucide-badge-dollar-sign", label: "Badge Dollar", keywords: "usd money price" },
      { name: "i-lucide-badge-cent", label: "Badge Cent", keywords: "money penny small change" },
      { name: "i-lucide-euro", label: "Euro", keywords: "eur money currency europe" },
      { name: "i-lucide-pound-sterling", label: "Pound", keywords: "gbp money currency uk britain" },
      { name: "i-lucide-japanese-yen", label: "Yen", keywords: "jpy money currency japan" },
      { name: "i-lucide-swiss-franc", label: "Swiss Franc", keywords: "chf money currency switzerland" },
      { name: "i-lucide-indian-rupee", label: "Rupee", keywords: "inr money currency india" },
      { name: "i-lucide-currency", label: "Currency", keywords: "money exchange foreign" },
      { name: "i-lucide-credit-card", label: "Credit Card", keywords: "payment debit visa mastercard" },
      { name: "i-lucide-receipt", label: "Receipt", keywords: "bill invoice ticket" },
      { name: "i-lucide-receipt-text", label: "Receipt Text", keywords: "bill invoice details" },
      { name: "i-lucide-nfc", label: "NFC", keywords: "contactless tap wireless payment" },
      { name: "i-lucide-scan-line", label: "Scan", keywords: "barcode payment pos" },
      { name: "i-lucide-qr-code", label: "QR Code", keywords: "scan payment transfer" },
      { name: "i-lucide-smartphone", label: "Smartphone", keywords: "phone mobile digital app" },
      { name: "i-lucide-laptop", label: "Laptop", keywords: "computer online digital" },
      { name: "i-lucide-globe", label: "Globe", keywords: "world international web online" },
      { name: "i-lucide-bitcoin", label: "Bitcoin", keywords: "crypto cryptocurrency digital" },
      { name: "i-lucide-trending-up", label: "Trending Up", keywords: "growth profit increase" },
      { name: "i-lucide-trending-down", label: "Trending Down", keywords: "loss decrease decline" },
      { name: "i-lucide-chart-line", label: "Line Chart", keywords: "graph analytics data" },
      { name: "i-lucide-chart-pie", label: "Pie Chart", keywords: "graph analytics breakdown" },
      { name: "i-lucide-chart-bar-stacked", label: "Bar Chart", keywords: "graph analytics comparison" },
      { name: "i-lucide-chart-area", label: "Area Chart", keywords: "graph analytics data" },
      { name: "i-lucide-percent", label: "Percent", keywords: "rate interest discount" },
      { name: "i-lucide-calculator", label: "Calculator", keywords: "math compute numbers" },
      { name: "i-lucide-scale", label: "Scale", keywords: "balance weight measure justice" },
      { name: "i-lucide-home", label: "Home", keywords: "house property mortgage rent alquiler vivienda" },
      { name: "i-lucide-door-open", label: "Door", keywords: "rent alquiler entrance housing room" },
      { name: "i-lucide-building-2", label: "Building", keywords: "office company corporate apartment" },
      { name: "i-lucide-plug", label: "Plug", keywords: "electricity power outlet luz edesur energy" },
      { name: "i-lucide-lightbulb", label: "Lightbulb", keywords: "electricity luz light energy power bill" },
      { name: "i-lucide-wifi", label: "WiFi", keywords: "internet connection wireless network broadband" },
      { name: "i-lucide-droplets", label: "Droplets", keywords: "water agua utility bill plumbing" },
      { name: "i-lucide-flame", label: "Flame", keywords: "fire gas heating hot utility bill" },
      { name: "i-lucide-phone", label: "Phone", keywords: "call telephone mobile bill plan celular" },
      { name: "i-lucide-tv", label: "TV", keywords: "television cable streaming screen entertainment" },
      { name: "i-lucide-wrench", label: "Wrench", keywords: "repair maintenance fix tool plumber" },
      { name: "i-lucide-spray-can", label: "Spray Can", keywords: "cleaning limpieza household products" },
      { name: "i-lucide-bath", label: "Bath", keywords: "bathroom cleaning wash tub shower" },
      { name: "i-lucide-shirt", label: "Shirt", keywords: "laundry clothes washing ropa lavanderia" },
      { name: "i-lucide-wind", label: "Wind", keywords: "fresh air ventilation clean breeze" },
      { name: "i-lucide-store", label: "Store", keywords: "shop retail business" },
      { name: "i-lucide-map-pin", label: "Map Pin", keywords: "location place address" },
      { name: "i-lucide-car", label: "Car", keywords: "vehicle drive auto transport" },
      { name: "i-lucide-bus-front", label: "Bus", keywords: "public transport commute" },
      { name: "i-lucide-train-front", label: "Train", keywords: "rail metro subway commute" },
      { name: "i-lucide-bike", label: "Bike", keywords: "bicycle cycle ride" },
      { name: "i-lucide-plane", label: "Plane", keywords: "flight travel airplane" },
      { name: "i-lucide-ship", label: "Ship", keywords: "boat ferry cruise sea" },
      { name: "i-lucide-truck", label: "Truck", keywords: "delivery freight shipping" },
      { name: "i-lucide-shopping-bag", label: "Shopping Bag", keywords: "buy retail purchase" },
      { name: "i-lucide-shopping-cart", label: "Shopping Cart", keywords: "buy retail grocery" },
      { name: "i-lucide-gift", label: "Gift", keywords: "present birthday surprise" },
      { name: "i-lucide-heart", label: "Heart", keywords: "love favorite health" },
      { name: "i-lucide-heart-pulse", label: "Heart Pulse", keywords: "health medical heartbeat vital signs monitor" },
      { name: "i-lucide-stethoscope", label: "Stethoscope", keywords: "doctor medical health checkup physician" },
      { name: "i-lucide-pill", label: "Pill", keywords: "medication medicine pharmacy drug prescription" },
      { name: "i-lucide-syringe", label: "Syringe", keywords: "injection vaccine medical needle shot" },
      { name: "i-lucide-thermometer", label: "Thermometer", keywords: "temperature fever medical health sick" },
      { name: "i-lucide-activity", label: "Activity", keywords: "vital signs health pulse medical monitor ecg" },
      { name: "i-lucide-cross", label: "Medical Cross", keywords: "health medical hospital first aid emergency" },
      { name: "i-lucide-ambulance", label: "Ambulance", keywords: "emergency medical hospital health rescue" },
      { name: "i-lucide-hospital", label: "Hospital", keywords: "medical health clinic building doctor" },
      { name: "i-lucide-brain", label: "Brain", keywords: "mental health psychology therapy mind thinking" },
      { name: "i-lucide-trophy", label: "Trophy", keywords: "sport win prize competition padel tournament" },
      { name: "i-lucide-medal", label: "Medal", keywords: "sport win achievement award" },
      { name: "i-lucide-dumbbell", label: "Dumbbell", keywords: "gym fitness workout exercise weights" },
      { name: "i-lucide-waves", label: "Waves", keywords: "water ocean swim surf wake beach" },
      { name: "i-lucide-snowflake", label: "Snowflake", keywords: "snow winter cold ski snowboard" },
      { name: "i-lucide-mountain", label: "Mountain", keywords: "hike outdoor nature trek climb" },
      { name: "i-lucide-tent", label: "Tent", keywords: "camping outdoor nature trip" },
      { name: "i-lucide-scissors", label: "Scissors", keywords: "haircut barber peluqueria cut salon" },
      { name: "i-lucide-bone", label: "Bone", keywords: "pet dog animal mascota treat" },
      { name: "i-lucide-paw-print", label: "Paw Print", keywords: "pet animal dog cat mascota" },
      { name: "i-lucide-cat", label: "Cat", keywords: "pet animal feline gato" },
      { name: "i-lucide-dog", label: "Dog", keywords: "pet animal canine perro" },
      { name: "i-lucide-gamepad-2", label: "Gamepad", keywords: "game play console gaming" },
      { name: "i-lucide-music", label: "Music", keywords: "song audio concert show night out" },
      { name: "i-lucide-headphones", label: "Headphones", keywords: "music audio listen spotify" },
      { name: "i-lucide-ticket", label: "Ticket", keywords: "event concert show movie entrada" },
      { name: "i-lucide-clapperboard", label: "Clapperboard", keywords: "movie film cinema" },
      { name: "i-lucide-graduation-cap", label: "Graduation Cap", keywords: "education school university course study learn" },
      { name: "i-lucide-book-open", label: "Book Open", keywords: "education read study learn library" },
      { name: "i-lucide-toy-brick", label: "Toy Brick", keywords: "toy play game kids pet" },
      { name: "i-lucide-hotel", label: "Hotel", keywords: "lodging stay room travel accommodation" },
      { name: "i-lucide-briefcase", label: "Briefcase", keywords: "work job business professional" },
      { name: "i-lucide-coffee", label: "Coffee", keywords: "cafe drink break morning" },
      { name: "i-lucide-utensils", label: "Utensils", keywords: "food restaurant eat dining" },
      { name: "i-lucide-beef", label: "Beef", keywords: "meat steak carniceria butcher food" },
      { name: "i-lucide-ham", label: "Ham", keywords: "meat pork carniceria butcher deli food" },
      { name: "i-lucide-drumstick", label: "Drumstick", keywords: "chicken meat pollo food" },
      { name: "i-lucide-sandwich", label: "Sandwich", keywords: "food lunch snack bread" },
      { name: "i-lucide-salad", label: "Salad", keywords: "food healthy vegetables verduras greens" },
      { name: "i-lucide-apple", label: "Apple", keywords: "fruit produce verduras fresh food healthy" },
      { name: "i-lucide-egg", label: "Egg", keywords: "food breakfast cooking kitchen" },
      { name: "i-lucide-cookie", label: "Cookie", keywords: "snack sweet dessert treat biscuit" },
      { name: "i-lucide-candy", label: "Candy", keywords: "sweet snack sugar treat kiosko" },
      { name: "i-lucide-ice-cream-cone", label: "Ice Cream", keywords: "dessert sweet frozen treat helado" },
      { name: "i-lucide-cake", label: "Cake", keywords: "dessert birthday sweet bakery torta" },
      { name: "i-lucide-pizza", label: "Pizza", keywords: "food delivery fast junk" },
      { name: "i-lucide-popcorn", label: "Popcorn", keywords: "snack cinema movie theater" },
      { name: "i-lucide-wine", label: "Wine", keywords: "drink alcohol bar bottle vino" },
      { name: "i-lucide-beer", label: "Beer", keywords: "drink alcohol bar cerveza pub" },
      { name: "i-lucide-martini", label: "Martini", keywords: "drink alcohol cocktail bar nightlife" },
      { name: "i-lucide-glass-water", label: "Glass Water", keywords: "drink water beverage hydrate" },
      { name: "i-lucide-cup-soda", label: "Soda", keywords: "drink soft beverage juice" },
      { name: "i-lucide-shopping-basket", label: "Shopping Basket", keywords: "grocery buy market food" },
      { name: "i-lucide-tag", label: "Tag", keywords: "label price category" },
      { name: "i-lucide-bookmark", label: "Bookmark", keywords: "save favorite mark" },
      { name: "i-lucide-flag", label: "Flag", keywords: "mark report milestone" },
      { name: "i-lucide-archive", label: "Archive", keywords: "storage old history" },
      { name: "i-lucide-box", label: "Box", keywords: "package container storage" },
      { name: "i-lucide-package", label: "Package", keywords: "delivery box shipment" },
      { name: "i-lucide-clock", label: "Clock", keywords: "time schedule watch" },
      { name: "i-lucide-calendar", label: "Calendar", keywords: "date schedule event plan" },
      { name: "i-lucide-bell", label: "Bell", keywords: "notification alert reminder" },
      { name: "i-lucide-shield", label: "Shield", keywords: "security protection insurance" },
      { name: "i-lucide-lock", label: "Lock", keywords: "secure private protected" },
      { name: "i-lucide-key", label: "Key", keywords: "access unlock password" },
      { name: "i-lucide-umbrella", label: "Umbrella", keywords: "insurance protection cover" },
      { name: "i-lucide-star", label: "Star", keywords: "favorite premium important" },
      { name: "i-lucide-zap", label: "Zap", keywords: "energy electric fast lightning" },
      { name: "i-lucide-gem", label: "Gem", keywords: "diamond luxury premium jewel" },
      { name: "i-lucide-award", label: "Award", keywords: "prize achievement badge" },
      { name: "i-lucide-crown", label: "Crown", keywords: "premium king royal vip" },
      { name: "i-lucide-sparkles", label: "Sparkles", keywords: "magic new special" },
      { name: "i-lucide-target", label: "Target", keywords: "goal aim objective budget" },
      { name: "i-lucide-file-text", label: "File Text", keywords: "document invoice fees paper" },
      { name: "i-lucide-file-check", label: "File Check", keywords: "document approved tax form" },
      { name: "i-lucide-undo-2", label: "Undo", keywords: "refund return revert back" },
      { name: "i-lucide-app-window", label: "App Window", keywords: "software application program desktop" },
      { name: "i-lucide-cloud", label: "Cloud", keywords: "hosting storage server saas" },
      { name: "i-lucide-monitor", label: "Monitor", keywords: "screen display computer desktop digital" },
      { name: "i-lucide-code-2", label: "Code", keywords: "programming developer software" },
      { name: "i-lucide-utensils-crossed", label: "Utensils Crossed", keywords: "kitchen cooking butcher knife restaurant" },
    ],
  },
  {
    title: "Crypto",
    icons: [
      { name: "i-simple-icons:bitcoin", label: "Bitcoin", keywords: "btc crypto cryptocurrency" },
      { name: "i-simple-icons:ethereum", label: "Ethereum", keywords: "eth crypto cryptocurrency" },
      { name: "i-simple-icons:bnbchain", label: "BNB", keywords: "bnb binance smart chain crypto" },
      { name: "i-simple-icons:solana", label: "Solana", keywords: "sol crypto cryptocurrency" },
      { name: "i-simple-icons:cardano", label: "Cardano", keywords: "ada crypto cryptocurrency" },
      { name: "i-simple-icons:polkadot", label: "Polkadot", keywords: "dot crypto cryptocurrency" },
      { name: "i-simple-icons:polygon", label: "Polygon", keywords: "matic crypto layer2" },
      { name: "i-simple-icons:litecoin", label: "Litecoin", keywords: "ltc crypto cryptocurrency" },
      { name: "i-simple-icons:dogecoin", label: "Dogecoin", keywords: "doge crypto meme" },
      { name: "i-simple-icons:monero", label: "Monero", keywords: "xmr crypto privacy" },
      { name: "i-simple-icons:ripple", label: "Ripple", keywords: "xrp crypto payment" },
      { name: "i-simple-icons:stellar", label: "Stellar", keywords: "xlm crypto payment" },
      { name: "i-simple-icons:tether", label: "Tether", keywords: "usdt stablecoin crypto" },
      { name: "i-simple-icons:ton", label: "TON", keywords: "toncoin telegram crypto" },
      { name: "i-simple-icons:chainlink", label: "Chainlink", keywords: "link oracle crypto defi" },
    ],
  },
  {
    title: "Brands",
    icons: [
      { name: "i-simple-icons:visa", label: "Visa", keywords: "card credit debit brand" },
      { name: "i-simple-icons:mastercard", label: "Mastercard", keywords: "card credit debit brand" },
      { name: "i-simple-icons:paypal", label: "PayPal", keywords: "payment online digital brand" },
      { name: "i-simple-icons:mercadopago", label: "MercadoPago", keywords: "mercadolibre payment argentina brand" },
      { name: "i-simple-icons:binance", label: "Binance", keywords: "crypto exchange digital brand" },
      { name: "i-simple-icons:wise", label: "Wise", keywords: "transfer international currency brand transferwise" },
      { name: "i-simple-icons:revolut", label: "Revolut", keywords: "neobank digital card brand" },
      { name: "i-simple-icons:payoneer", label: "Payoneer", keywords: "payment freelance international brand" },
    ],
  },
];

/** Flat list of every icon across all sections, used for search and label lookup. */
export const ALL_ICONS = ICON_SECTIONS.flatMap((s) => s.icons);
